# Configuration for the-welcome-bot - https://github.com/bash-bot/the-welcome-bot

# Message for a new user who open an issue
issueOpen: >
  Welcome to the project!
  Thanks and congrats for opening your very first issue in this project.
  You may submit a PR on the same if you like!
  Hope you have a great time here :)

# Message for a new user who comments on an issue
issueComment: >
  Welcome to the project!
  Thanks and congrats for your very first comment on this project.
  Checkout the ReadMe for more details on it.
  Want to contribute? Make an issue or submit a PR.
  Hope you have a great time here :)

# Message for a new user who opens a PR
prOpen: >
  Welcome to the project!
  Thankyou and congarts for your first PR on this project.
  We will review it soon!
  Till then you can checkout the ReadMe for more details on it.
  Hope you have a great time here :)

# Default message for a new user
welcomeMessage: >
  Welcome to the project! Feel free to explore it.
  Checkout the ReadMe for more details on it.
  Want to contribute? Make an issue or submit a PR.
  You can check the contributing guides and code of conduct for the same.
  Hope you have a great time here :)
