disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
- colon
- implicit_getter
- empty_enum_arguments
opt_in_rules: # some rules are only opt-in
# Find all the available rules by running: swiftlint rules
- trailing_semicolon
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Example/Pods
- Example/StepperView/AppDelegate.swift
- Example/StepperView_Watch Extension/ComplicationController.swift
- Example/StepperView_Watch Extension/ExtensionDelegate.swift
included: # paths to include during linting. `--path` is ignored if present.
- Sources
- Example
- Tests
identifier_name:
  excluded:
    - id
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 2
line_length: 160
