language: swift
xcode_workspace: Example/StepperView.xcworkspace
xcode_scheme: StepperView-Example
osx_image: xcode11.3
podfile: Example/Podfile
before_install:
  - gem install cocoapods
  - gem install jazzy
  - pod repo update
script: xcodebuild test -workspace Example/StepperView.xcworkspace -scheme StepperView-Example -destination "platform=iOS Simulator,OS=13.3,name=iPhone 11" ONLY_ACTIVE_ARCH=NO -quiet


